### ISSUE TITLE
Windows 10 + Conda = Issue

### ISSUE THREAD

**Issue by snyguy** [allenfrostline/Poker#5]
I looked at sources, and tried to uninstall and re-install matplotlib with conda, but it still did not work.

I am simply going to use Linux for now, but this is an issue that should be fixed. Maybe this belongs in Anaconda + MatPlotLib as well.

(base) PS C:\Users\Admin\Downloads\Poker-master\Poker-master> python poker_gui.py
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\backends\tkagg.py", line 27, in blit
    dataptr, colormode, bboxptr)
_tkinter.TclError: invalid command name "PyAggImagePhoto"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "poker_gui.py", line 523, in <module>
    g = Game(n_players=9, buy_in=10, seed='random')
  File "poker_gui.py", line 44, in __init__
    self.__newGame()
  File "poker_gui.py", line 191, in __newGame
    self.__newRound(blind=True)
  File "poker_gui.py", line 295, in __newRound
    bet = self.__bet(i, n_round, blind)
  File "poker_gui.py", line 441, in __bet
    _ = drawFigure(window.FindElement('_CANVAS_').TKCanvas, fig)
  File "C:\Users\Admin\Downloads\Poker-master\Poker-master\misc.py", line 478, in drawFigure
    tkagg.blit(photo, figure_canvas_agg.get_renderer()._renderer, colormode=2)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\backends\tkagg.py", line 28, in blit
    except tk.TclError:
AttributeError: '_tkinter.tkapp' object has no attribute 'TclError'

**Comment by allenfrostline** [comment]
@snyguy Sorry I don't think this works on Windows. All development was done within MacOS environments and is not transferrable out-of-box due to the fact that some packages are only for Mac. You can find alternative packages and write your own GUI if you want, wrt a Windows machine.
